package com.eight.puzzle.view;

import com.eight.puzzle.controller.Controller;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Marques
 */
public class Game extends javax.swing.JFrame {
    private Controller controller = new Controller();
    private int movementCounter = 0;
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        this.controller.initBoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        button_3 = new javax.swing.JButton();
        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        gameLogo = new javax.swing.JLabel();
        startGame = new javax.swing.JButton();
        resetGame = new javax.swing.JButton();
        movementsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8 Puzzle");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        button_3.setBackground(new java.awt.Color(53, 151, 102));
        button_3.setFont(new java.awt.Font("Gill Sans", 0, 24)); // NOI18N
        button_3.setText("3");
        button_3.setEnabled(false);
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });

        button_1.setBackground(new java.awt.Color(53, 151, 102));
        button_1.setFont(new java.awt.Font("Gill Sans", 0, 24)); // NOI18N
        button_1.setText("1");
        button_1.setEnabled(false);
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        button_2.setBackground(new java.awt.Color(53, 151, 102));
        button_2.setFont(new java.awt.Font("Gill Sans", 0, 24)); // NOI18N
        button_2.setText("2");
        button_2.setEnabled(false);
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });

        button_6.setBackground(new java.awt.Color(53, 151, 102));
        button_6.setFont(new java.awt.Font("Gill Sans", 0, 24)); // NOI18N
        button_6.setText("6");
        button_6.setEnabled(false);
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_6ActionPerformed(evt);
            }
        });

        button_4.setBackground(new java.awt.Color(53, 151, 102));
        button_4.setFont(new java.awt.Font("Gill Sans", 0, 24)); // NOI18N
        button_4.setText("4");
        button_4.setEnabled(false);
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_4ActionPerformed(evt);
            }
        });

        button_5.setBackground(new java.awt.Color(53, 151, 102));
        button_5.setFont(new java.awt.Font("Gill Sans", 0, 24)); // NOI18N
        button_5.setText("5");
        button_5.setEnabled(false);
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5ActionPerformed(evt);
            }
        });

        button_9.setBackground(new java.awt.Color(53, 151, 102));
        button_9.setFont(new java.awt.Font("Gill Sans", 0, 24)); // NOI18N
        button_9.setEnabled(false);
        button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_9ActionPerformed(evt);
            }
        });

        button_8.setBackground(new java.awt.Color(53, 151, 102));
        button_8.setFont(new java.awt.Font("Gill Sans", 0, 24)); // NOI18N
        button_8.setText("8");
        button_8.setEnabled(false);
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_8ActionPerformed(evt);
            }
        });

        button_7.setBackground(new java.awt.Color(53, 151, 102));
        button_7.setFont(new java.awt.Font("Gill Sans", 0, 24)); // NOI18N
        button_7.setText("7");
        button_7.setEnabled(false);
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gameLogo.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        gameLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/puzzle_image.png"))); // NOI18N

        startGame.setText("Iniciar");
        startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameActionPerformed(evt);
            }
        });

        resetGame.setText("Resetar");
        resetGame.setEnabled(false);
        resetGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetGameActionPerformed(evt);
            }
        });

        movementsLabel.setText("Total de Movimentos: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gameLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(startGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resetGame, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movementsLabel))))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(movementsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startGame, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetGame, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameActionPerformed
        this.updateBoard();
        this.resetGame.setEnabled(true);
        
        this.button_1.setEnabled(true);
        this.button_2.setEnabled(true);
        this.button_3.setEnabled(true);
        this.button_4.setEnabled(true);
        this.button_5.setEnabled(true);
        this.button_6.setEnabled(true);
        this.button_7.setEnabled(true);
        this.button_8.setEnabled(true);
        this.button_9.setEnabled(true);
        
    }//GEN-LAST:event_startGameActionPerformed

    private void resetGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetGameActionPerformed
        this.controller.initBoard();
        this.movementCounter = 0;
        this.updateBoard();
    }//GEN-LAST:event_resetGameActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
        boolean moveBlock = this.controller.moveBlocks(0, 0);
        
        if(moveBlock) {
            this.movementCounter += 1;
            this.updateBoard();
            
            if(this.controller.checkWin(this.controller.getBlocksOfBoard())) {
                this.displayVictoryMessage();
            }
        }
    }//GEN-LAST:event_button_1ActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
        boolean moveBlock = this.controller.moveBlocks(0, 1);
        
        if(moveBlock) {
            this.movementCounter += 1;
            this.updateBoard();
            
            if(this.controller.checkWin(this.controller.getBlocksOfBoard())) {
                this.displayVictoryMessage();
            }
        }
    }//GEN-LAST:event_button_2ActionPerformed

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
        boolean moveBlock = this.controller.moveBlocks(0, 2);
        
        if(moveBlock) {
            this.movementCounter += 1;
            this.updateBoard();
        
            if(this.controller.checkWin(this.controller.getBlocksOfBoard())) {
                this.displayVictoryMessage();
            }
        }
    }//GEN-LAST:event_button_3ActionPerformed

    private void button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_4ActionPerformed
        boolean moveBlock = this.controller.moveBlocks(1, 0);
        
        if(moveBlock) {
            this.movementCounter += 1;
            this.updateBoard();
        
            if(this.controller.checkWin(this.controller.getBlocksOfBoard())) {
                this.displayVictoryMessage();
            }
        }
    }//GEN-LAST:event_button_4ActionPerformed

    private void button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5ActionPerformed
        boolean moveBlock = this.controller.moveBlocks(1, 1);
        
        if(moveBlock) {
            this.movementCounter += 1;
            this.updateBoard();
        
            if(this.controller.checkWin(this.controller.getBlocksOfBoard())) {
                this.displayVictoryMessage();
            }
        }
    }//GEN-LAST:event_button_5ActionPerformed

    private void button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_6ActionPerformed
        boolean moveBlock = this.controller.moveBlocks(1, 2);
        
        if(moveBlock) {
            this.movementCounter += 1;
            this.updateBoard();
        
            if(this.controller.checkWin(this.controller.getBlocksOfBoard())) {
                this.displayVictoryMessage();
            }
        }
    }//GEN-LAST:event_button_6ActionPerformed

    private void button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_7ActionPerformed
        boolean moveBlock = this.controller.moveBlocks(2, 0);
        
        if(moveBlock) {
            this.movementCounter += 1;
            this.updateBoard();
        
            if(this.controller.checkWin(this.controller.getBlocksOfBoard())) {
                this.displayVictoryMessage();
            }
        }
    }//GEN-LAST:event_button_7ActionPerformed

    private void button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_8ActionPerformed
        boolean moveBlock = this.controller.moveBlocks(2, 1);
        
        if(moveBlock) {
            this.movementCounter += 1;
            this.updateBoard();
        
            if(this.controller.checkWin(this.controller.getBlocksOfBoard())) {
                this.displayVictoryMessage();
            }
        }
    }//GEN-LAST:event_button_8ActionPerformed

    private void button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_9ActionPerformed
        boolean moveBlock = this.controller.moveBlocks(2, 2);
        
        if(moveBlock) {
            this.movementCounter += 1;
            this.updateBoard();
        
            if(this.controller.checkWin(this.controller.getBlocksOfBoard())) {
                this.displayVictoryMessage();
            }
        }
    }//GEN-LAST:event_button_9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Game game = new Game();
                game.setLocationRelativeTo(null);
                game.setVisible(true);
            }
        });
    }
    
     private void updateBoard() {
        Integer[][] blocks = this.controller.getBlocksOfBoard();
        this.button_1.setText(this.checkIfZero(blocks[0][0]));
        this.button_2.setText(this.checkIfZero(blocks[0][1]));
        this.button_3.setText(this.checkIfZero(blocks[0][2]));
        this.button_4.setText(this.checkIfZero(blocks[1][0]));
        this.button_5.setText(this.checkIfZero(blocks[1][1]));
        this.button_6.setText(this.checkIfZero(blocks[1][2]));
        this.button_7.setText(this.checkIfZero(blocks[2][0]));
        this.button_8.setText(this.checkIfZero(blocks[2][1]));
        this.button_9.setText(this.checkIfZero(blocks[2][2]));
        
        this.movementsLabel.setText("Total de Movimentos: " + this.movementCounter);
    }
    
    private String checkIfZero(Integer value) {
        return value != 0 ? Integer.toString(value) : "";
    }
    
    private void displayVictoryMessage() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/assets/congratulation.png"));
        
        JOptionPane.showMessageDialog(
            rootPane, 
            "Parabéns! Você solucionou o Puzzle!\nTotal de cliques: " + this.movementCounter, 
            "Parabéns!  🎉🎯",
            JOptionPane.INFORMATION_MESSAGE,
            icon
        );
        
        this.controller.initBoard();
        this.movementCounter = 0;
        this.updateBoard();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JLabel gameLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel movementsLabel;
    private javax.swing.JButton resetGame;
    private javax.swing.JButton startGame;
    // End of variables declaration//GEN-END:variables
}
